version: '3.8' 

services: 

  api:
    build: . 
    ports:
      - "3000:3000" 
    environment:
      DATABASE_URL: postgresql://myuser:mysecretpassword@db:5432/minileggal
    depends_on:
      - db 

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: minileggal
    volumes:
      - postgres-data:/var/lib/postgresql/data 

volumes: 
  postgres-data: